### ISSUE TITLE
Invalid parity: Integration requested parity NONE but you have EVEN!

### ISSUE THREAD

**Issue by mazay** [athom-tech/athom-configs#79]
Newly purchased V3 plugs are throwing errors with ESPHome version 2024.8.3:
```
[22:26:29][I][app:100]: ESPHome version 2024.8.3 compiled on Sep 10 2024, 15:41:08
[22:26:29][I][app:102]: Project Athom_Technology.Smart_Plug_V3 version v1.0.3
[22:26:29][E][uart:029]:   Invalid parity: Integration requested parity NONE but you have EVEN!
[22:26:39][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
```

As far as I can tell the `uart` block is missing in V3 config. Please advise what it should look like.

V2 block for reference - https://github.com/athom-tech/athom-configs/blob/main/athom-smart-plug-v2.yaml#L111-L113

**Comment by Roving-Ronin** [comment]
v3 has the UART code:

```
uart:
  rx_pin: GPIO20
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: EVEN
```
at: https://github.com/athom-tech/esp32-configs/blob/e4912eb6e107509176f5e6d5b25c9aec9ff16639/athom-smart-plug.yaml#L99

Also worth checking closed issues first:

https://github.com/athom-tech/esp32-configs/issues/2

https://github.com/esphome/issues/issues/4529#issuecomment-1822283401

**Comment by mazay** [comment]
not sure how I missed closed issues, they did not appear in the search results for me...

also, I didn't realise the v3 config was in another repo

so it's about `parity` settings then, should it be updated?

**Comment by mazay** [comment]
according to [this](https://github.com/athom-tech/esp32-configs/issues/9) the setting is correct

closing anyway as it does not belong to this repo
